Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2022-12, with the labels that each got.

#23 Add typescript support
  jsconfig.json
  package-lock.json
  package.json
  tests/dummy/app/config/environment.d.ts
  tsconfig.json
  types/dummy/index.d.ts
  types/ember-data/types/registries/model.d.ts
  types/global.d.ts
Labels: internal

#24 Trigger date plugin correctly
  addon/components/rdfa-date-plugin/rdfa-date-plugin-card.js
Labels: bug

#25 Replace citaten-plugin.citaten-plugin by citaten-plugin
  addon/components/citaten-plugin/citaat-card.hbs
  addon/components/citaten-plugin/citations/decision-detail.hbs
  addon/components/citaten-plugin/helpers/alert-load-error.hbs
  addon/components/citaten-plugin/helpers/alert-no-items.hbs
Labels: bug

#28 Convert insert-variable plugin to prosemirror based editor.
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
  addon/components/insert-variable-plugin/insert-variable-card.hbs
  addon/components/insert-variable-plugin/insert-variable-card.js
  addon/components/insert-variable-plugin/insert-variable-card.ts
  addon/components/rdfa-date-plugin/card.ts
  addon/components/standard-template-plugin/template-provider.ts
  addon/components/table-of-contents-plugin/card.js
  addon/components/table-of-contents-plugin/inline-components/table-of-contents.js
  addon/components/template-variable-plugin/template-variable-card.hbs
  addon/components/template-variable-plugin/template-variable-card.js
  addon/components/template-variable-plugin/template-variable-card.ts
  addon/plugins/insert-variable-plugin.js
  addon/plugins/insert-variable-plugin.ts
  addon/plugins/template-variable-plugin.js
  addon/plugins/template-variable-plugin.ts
  addon/utils/instantiate-uuids.ts
  addon/utils/variable-plugins/default-variable-types.ts
  tests/dummy/app/controllers/application.ts
Labels: enhancement

#31 Convert roadsign-regulation plugin to prosemirror based editor.
  addon/components/roadsign-regulation-plugin/expanded-measure.js
  addon/components/roadsign-regulation-plugin/expanded-measure.ts
  addon/components/roadsign-regulation-plugin/measure-template.js
  addon/components/roadsign-regulation-plugin/measure-template.ts
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.hbs
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.js
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.js
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/components/roadsign-regulation-plugin/roadsigns-pagination.ts
  addon/components/roadsign-regulation-plugin/roadsigns-table.js
  addon/components/roadsign-regulation-plugin/roadsigns-table.ts
  addon/models/instruction.js
  addon/models/instruction.ts
  addon/models/measure.js
  addon/models/measure.ts
  addon/models/sign.js
  addon/models/sign.ts
  addon/plugins/roadsign-regulation-plugin.ts
  addon/services/roadsign-registry.js
  addon/services/roadsign-registry.ts
  addon/utils/roadsign-regulation-plugin/fetchData.ts
  addon/utils/roadsign-regulation-plugin/includeInstructions.js
  addon/utils/roadsign-regulation-plugin/includeInstructions.ts
  package-lock.json
  package.json
  tests/dummy/app/controllers/application.ts
Labels: enhancement

#33 feature/dev utils
  index.js
  package-lock.json
  package.json
  tests/dummy/app/controllers/application.ts
Labels: enhancement

#35 converting the besluit-plugin to new API
  addon/commands/besluit-plugin/get-article-nodes-for-besluit.ts
  addon/commands/besluit-plugin/index.ts
  addon/commands/besluit-plugin/insert-article.ts
  addon/commands/besluit-plugin/insert-title.ts
  addon/commands/besluit-plugin/move-article.ts
  addon/commands/besluit-plugin/recalculate-article-numbers.ts
  addon/components/besluit-plugin/besluit-context-card.hbs
  addon/components/besluit-plugin/besluit-context-card.ts
  addon/components/besluit-plugin/besluit-plugin-card.hbs
  addon/components/besluit-plugin/besluit-plugin-card.ts
  addon/plugins/besluit-plugin.ts
  addon/plugins/citation-plugin/index.ts
  addon/services/standard-template-plugin.ts
  addon/utils/besluit-plugin/get-title-for-decision.ts
  app/components/besluit-plugin/besluit-context-card.js
  app/components/besluit-plugin/besluit-plugin-card.js
  tests/dummy/app/controllers/application.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement
