Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-07, with the labels that each got.

#193 Update ember-velcro to 2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#195 chore(deps): bump editor to 4.0.0
  CHANGELOG.md
  package-lock.json
  package.json
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tsconfig.json
Labels: internal

#192 Addition of a document-title plugin
  CHANGELOG.md
  addon/components/document-title-plugin/insert-title-card.hbs
  addon/components/document-title-plugin/insert-title-card.ts
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/document-title-plugin/commands/insert-document-title.ts
  addon/plugins/document-title-plugin/nodes/document-title.ts
  addon/plugins/document-title-plugin/nodes/index.ts
  addon/utils/_private/find-insertion-range.ts
  app/components/document-title-plugin/insert-title-card.js
  app/styles/document-title-plugin.scss
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/styles/app.scss
  tests/dummy/app/templates/regulatory-statement-sample.hbs
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#197 Fix ember 3.28 compatibility of number variable node
  CHANGELOG.md
  addon/components/variable-number/number.ts
Labels: bug

#198 GN-4273: article-structure plugin documentation
  CHANGELOG.md
  README.md
Labels: documentation

#206 GN-4418: display number numerically if too big to convert to words
  CHANGELOG.md
  addon/components/variable-number/number.ts
  addon/plugins/variable-plugin/nodes.ts
  addon/plugins/variable-plugin/utils/number-to-words.ts
Labels: bug

#217 Revert ember-auto-import to 2.5.0 and pin ember-auto-import to 2.5.x
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal
