Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-04, with the labels that each got.

#129 fix(decision-nodes): make nodespecs unambiguous
  CHANGELOG.md
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#128 fix(citation): make plugin trigger correctly when `doc` is passed as an allowed nodeType
  CHANGELOG.md
  README.md
  addon/components/citation-plugin/citation-insert.ts
Labels: bug

#132 Explain the removal options for structures
  CHANGELOG.md
  addon/components/article-structure-plugin/structure-card.hbs
  addon/components/article-structure-plugin/structure-card.ts
  addon/components/hover-tooltip.hbs
  addon/components/hover-tooltip.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/chapter.ts
  addon/plugins/article-structure-plugin/structures/section.ts
  addon/plugins/article-structure-plugin/structures/subsection.ts
  addon/plugins/article-structure-plugin/structures/title.ts
  app/components/hover-tooltip.js
  tests/dummy/app/routes/application.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#131 Bugfix/solve duplicate node title
  CHANGELOG.md
  addon/plugins/besluit-plugin/commands/insert-title.ts
  addon/plugins/standard-template-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug, breaking

#125 Change date labels based on designer feedback
  CHANGELOG.md
  addon/components/rdfa-date-plugin/card.hbs
  addon/plugins/rdfa-date-plugin/index.ts
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
Labels: enhancement

#127 Feature/improve toc scroll
  CHANGELOG.md
  addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.ts
  addon/plugins/table-of-contents-plugin/index.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
Labels: enhancement
