Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-09, with the labels that each got.

#273 GN-4330: allow per-instance config of single/multi-select styles
  CHANGELOG.md
  addon/components/variable-plugin/codelist/edit.ts
  addon/components/variable-plugin/codelist/insert.hbs
  addon/components/variable-plugin/codelist/insert.ts
  addon/plugins/variable-plugin/utils/attribute-parsers.ts
  addon/plugins/variable-plugin/variables/codelist.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#284 Move changelog check to seperate CI pipeline
  .woodpecker/.changelog.yml
  .woodpecker/.test.yml
  CHANGELOG.md
Labels: internal

#283 Enable additional prosemirror plugins in dummy apps
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
Labels: internal

#288 Update editor from 5.2.0 to 5.3.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#285 Use modifiers in number-variable
  CHANGELOG.md
  addon/components/variable-plugin/number/nodeview.hbs
  addon/components/variable-plugin/number/nodeview.ts
Labels: breaking

#290 GN-4479: make address node work properly inside a location variable
  .changeset/shaggy-books-report.md
  addon/components/rdfa-date-plugin/date.hbs
  addon/components/variable-plugin/address/edit.ts
  addon/components/variable-plugin/address/insert.hbs
  addon/components/variable-plugin/address/insert.ts
  addon/components/variable-plugin/address/nodeview.hbs
  addon/components/variable-plugin/location/nodeview.hbs
  addon/components/variable-plugin/location/nodeview.ts
  addon/components/variable-plugin/number/nodeview.hbs
  addon/components/variable-plugin/variable/nodeview.hbs
  addon/plugins/variable-plugin/variables/location.ts
  app/components/variable-plugin/location/nodeview.js
  app/styles/variable-plugin.scss
Labels: enhancement

#303 Update `@lblod/ember-rdfa-editor` to version 6.0.0
  .changeset/seven-trainers-wink.md
  .changeset/shaggy-kiwis-talk.md
  addon/plugins/rdfa-date-plugin/nodes/date.ts
  addon/plugins/table-of-contents-plugin/nodes/table-of-contents.ts
  addon/plugins/template-comments-plugin/node.ts
  addon/plugins/variable-plugin/variables/address.ts
  addon/plugins/variable-plugin/variables/codelist.ts
  addon/plugins/variable-plugin/variables/location.ts
  addon/plugins/variable-plugin/variables/number.ts
  addon/plugins/variable-plugin/variables/text.ts
  package-lock.json
  package.json
Labels: internal

#307 GN-4502: allow municipality and street field of address plugin to be cleared
  .changeset/nine-otters-behave.md
  addon/components/variable-plugin/address/edit.hbs
Labels: bug
