Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-06, with the labels that each got.

#156 Move tracked-toolbox to dependencies
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#159 change problematic type in citation that made it to break with new ember
  CHANGELOG.md
  addon/plugins/citation-plugin/utils/vlaamse-codex.ts
Labels: bug

#175 Update typescript to 5.0.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#176 GN-4365: use dutch instead of english for static version of table-of-contents node
  CHANGELOG.md
  addon/plugins/table-of-contents-plugin/nodes/table-of-contents.ts
Labels: bug

#177 GN-4200: Bugfix/toc scroll not working
  CHANGELOG.md
  README.md
  addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.ts
  addon/plugins/table-of-contents-plugin/index.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
Labels: bug, breaking

#185 Bump date fns to 2.30
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#184 GN-4351: fix roadsign-regulation code filtering
  CHANGELOG.md
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
Labels: bug
