Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-01, with the labels that each got.

#39 Remove paragraphs from toc
  addon/plugins/table-of-contents-plugin/utils/constants.ts
Labels: enhancement

#40 Major rework of article-structure plugin
  addon/components/article-structure-plugin/article-structure-card.hbs
  addon/components/article-structure-plugin/article-structure-card.ts
  addon/components/article-structure-plugin/structure-card.hbs
  addon/components/article-structure-plugin/structure-card.ts
  addon/plugins/article-structure-plugin/commands/delete-structure.ts
  addon/plugins/article-structure-plugin/commands/index.ts
  addon/plugins/article-structure-plugin/commands/insert-article-structure.ts
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
  addon/plugins/article-structure-plugin/commands/move-structure.ts
  addon/plugins/article-structure-plugin/commands/recalculate-structure-numbers.ts
  addon/plugins/article-structure-plugin/commands/remove-structure.ts
  addon/plugins/article-structure-plugin/commands/unwrap-structure.ts
  addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
  addon/plugins/article-structure-plugin/constants.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/chapter.ts
  addon/plugins/article-structure-plugin/structures/index.ts
  addon/plugins/article-structure-plugin/structures/section.ts
  addon/plugins/article-structure-plugin/structures/structure-header.ts
  addon/plugins/article-structure-plugin/structures/subsection.ts
  addon/plugins/article-structure-plugin/structures/title.ts
  addon/plugins/article-structure-plugin/utils/constants.ts
  addon/plugins/article-structure-plugin/utils/defaults.ts
  addon/plugins/article-structure-plugin/utils/namespace.ts
  addon/plugins/article-structure-plugin/utils/options-with-defaults.ts
  addon/plugins/article-structure-plugin/utils/romanize.ts
  addon/plugins/article-structure-plugin/utils/structure.ts
  addon/plugins/article-structure-plugin/utils/validate-datastore.ts
  package-lock.json
  package.json
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#37 Fix besluit plugin numbering
  addon/components/besluit-plugin/besluit-plugin-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/plugins/besluit-plugin/commands/insert-article.ts
Labels: bug

#41 Update editor to 1.0.0-alpha.13
  package-lock.json
  package.json
Labels: internal

#42 Remove redundant context from article-structure plugin
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
  addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/chapter.ts
  addon/plugins/article-structure-plugin/structures/section.ts
  addon/plugins/article-structure-plugin/structures/subsection.ts
  addon/plugins/article-structure-plugin/structures/title.ts
Labels: internal

#46 Update insert-structure command so it looks forward for the next best position to insert
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/article-structure-plugin/structures/structure-header.ts
  addon/plugins/article-structure-plugin/utils/structure.ts
Labels: enhancement

#48 Roadsign regulation plugin rework
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: enhancement

#47 Implement besluit articles using article-structure plugin
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/standard-template-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: enhancement

#49 Avoid using the datastore on the besluit type plugin
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
Labels: enhancement

#44 Rework of date plugin with custom date NodeSpec
  addon/components/rdfa-date-plugin/card.ts
  addon/components/rdfa-date-plugin/date-time-picker.ts
  addon/components/rdfa-date-plugin/insert.hbs
  addon/components/rdfa-date-plugin/insert.ts
  addon/plugins/rdfa-date-plugin/commands/index.ts
  addon/plugins/rdfa-date-plugin/commands/modify-date.ts
  addon/plugins/rdfa-date-plugin/nodes/date.ts
  addon/plugins/rdfa-date-plugin/nodes/index.ts
  app/styles/date-plugin.scss
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/styles/app.scss
Labels: enhancement, breaking

#52 Remove datastore dependency from snippet plugin
  addon/components/import-snippet-plugin/card.ts
Labels: internal

#51 Custom roadsign regulation node
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/plugins/roadsign-regulation-plugin/nodes.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
  addon/utils/constants.ts
  addon/utils/namespace.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: enhancement

#56 Add space before 'met zonale geldigheid'
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
Labels: bug

#55 Ensure that the citation type is preserved between the sidebar card and the modal
  addon/components/citation-plugin/citation-card.hbs
  addon/components/citation-plugin/citation-insert.hbs
  addon/components/citation-plugin/citation-insert.ts
  addon/components/citation-plugin/citations/search-modal.hbs
  addon/components/citation-plugin/citations/search-modal.ts
Labels: bug

#60 Update editor to 1.0.0-beta.1
  addon/plugins/citation-plugin/index.ts
  package-lock.json
  package.json
Labels: internal

#58 Add backwards compatible parsing rule to article_paragraph
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/utils/structure.ts
Labels: bug

#62 feat(citation): make citation plugin datastore-independent
  addon/plugins/citation-plugin/index.ts
  addon/plugins/citation-plugin/nodes/motivation.ts
  addon/utils/changed-descendants.ts
  addon/utils/constants.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: enhancement, breaking

#43 Feature/template nodes
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
  addon/components/import-snippet-plugin/card.ts
  addon/components/rdfa-date-plugin/card.ts
  addon/components/rdfa-date-plugin/date-time-picker.ts
  addon/components/rdfa-date-plugin/insert.hbs
  addon/components/rdfa-date-plugin/insert.ts
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/citation-plugin/nodes/motivation.ts
  addon/plugins/rdfa-date-plugin/commands/index.ts
  addon/plugins/rdfa-date-plugin/commands/modify-date.ts
  addon/plugins/rdfa-date-plugin/nodes/date.ts
  addon/plugins/rdfa-date-plugin/nodes/index.ts
  addon/plugins/roadsign-regulation-plugin/nodes.ts
  addon/plugins/standard-template-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
  addon/utils/constants.ts
  addon/utils/namespace.ts
  app/styles/date-plugin.scss
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/styles/app.scss
Labels: enhancement

#65 Update editor to 1.0.0-beta.4
  package-lock.json
  package.json
Labels: internal

#64 Replace paragraphs by block in content specifiers and fix roadsign-regulation parsing rule
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/chapter.ts
  addon/plugins/article-structure-plugin/structures/section.ts
  addon/plugins/article-structure-plugin/structures/subsection.ts
  addon/plugins/article-structure-plugin/structures/title.ts
  addon/plugins/roadsign-regulation-plugin/nodes.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
Labels: bug

#68 Update editor to 1.0.0-beta.5
  package-lock.json
  package.json
Labels: internal

#69 Add enter handler to variable editor view
  addon/components/variable-plugin/variable.ts
Labels: enhancement

#70 Add onClick handler to variable pill that focuses the variable if it is not yet focused
  addon/components/au-dropdown-pill.hbs
  addon/components/au-dropdown-pill.ts
  addon/components/variable-plugin/variable.hbs
  addon/components/variable-plugin/variable.ts
  app/components/au-dropdown-pill.js
Labels: enhancement

#71 Avoid writing out p tags for nodes different than paragraph
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#72 Enable word-break as break-all on variable contenteditable
  app/styles/variable-plugin.scss
Labels: bug

#73 Make besluit title optional
  addon/components/besluit-plugin/besluit-context-card.hbs
  addon/components/besluit-plugin/besluit-context-card.ts
  addon/components/besluit-plugin/besluit-plugin-card.hbs
  addon/components/besluit-plugin/besluit-plugin-card.ts
  addon/plugins/besluit-plugin/commands/get-article-nodes-for-besluit.ts
  addon/plugins/besluit-plugin/commands/index.ts
  addon/plugins/besluit-plugin/commands/insert-article.ts
  addon/plugins/besluit-plugin/commands/insert-title.ts
  addon/plugins/besluit-plugin/commands/move-article.ts
  addon/plugins/besluit-plugin/commands/recalculate-article-numbers.ts
  addon/plugins/besluit-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
  tests/dummy/app/controllers/besluit-sample.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: internal

#75 Article-structure-plugin: structure insertion improvements
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: enhancement

#76 Replace insert-title button with warning that pops up when a decision title is missing
  addon/components/besluit-plugin/besluit-plugin-card.hbs
  addon/plugins/besluit-plugin/index.ts
  app/styles/besluit-plugin.scss
  tests/dummy/app/styles/app.scss
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#78 Improve behavior of decision nodes
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#79 fix(template): improve template insertion behavior
  addon/components/standard-template-plugin/template-provider.ts
Labels: bug

#80 fix(decision-type): don't remove the type we just added if it happens to be the same as the old one
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
Labels: bug

#81 Wrap-structure-content: return false if structure is not a wrapper
  addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
Labels: bug

#82 Add typeof and property to article_paragraph attrs
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Labels: bug

#83 Update editor to 1.0.0
  package-lock.json
  package.json
Labels: internal

#85 Update besluit-type pill after having fetched the besluit types
  addon/components/besluit-type-plugin/toolbar-dropdown.hbs
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
  package-lock.json
  package.json
Labels: bug

#86 Ensure new roadsign regulations are scrolled into view after insertion
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.hbs
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
Labels: bug
