Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2023-02, with the labels that each got.

#90 show error when the date format is empty
  addon/components/rdfa-date-plugin/card.hbs
  addon/components/rdfa-date-plugin/card.ts
Labels: enhancement

#92 Update editor to 2.0.1
  addon/plugins/article-structure-plugin/commands/insert-structure.ts
  addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
  package-lock.json
  package.json
Labels: internal

#74 Feature/recreate uuids on paste
  addon/plugins/variable-plugin/nodes.ts
Labels: enhancement

#93 Make headers and content nodes of structures isolating and defining
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/structure-header.ts
  addon/plugins/article-structure-plugin/utils/structure.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: enhancement

#94 feat(dates): add nice error messages to custom format box
  addon/components/rdfa-date-plugin/card.hbs
  addon/components/rdfa-date-plugin/card.ts
  addon/components/rdfa-date-plugin/date-time-picker.hbs
  addon/components/rdfa-date-plugin/date-time-picker.ts
  addon/components/rdfa-date-plugin/help-modal.hbs
  addon/components/rdfa-date-plugin/help-modal.ts
  addon/components/rdfa-date-plugin/insert.ts
  addon/plugins/rdfa-date-plugin/index.ts
  addon/plugins/rdfa-date-plugin/nodes/date.ts
  addon/plugins/rdfa-date-plugin/utils.ts
  app/components/rdfa-date-plugin/help-modal.js
  app/styles/date-plugin.scss
  package-lock.json
  package.json
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement, breaking

#95 Move ember-velcro to hard dependencies
  package-lock.json
  package.json
Labels: bug

#97 Fix: disallow splitting of besluit node
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#98 Improve citation plugin regex and improve citation type matching
  addon/plugins/citation-plugin/index.ts
  addon/plugins/citation-plugin/utils/legislation-types.ts
  addon/plugins/citation-plugin/utils/process-match.ts
Labels: enhancement

#100 Prevent splitting of besluit related nodes
  addon/plugins/standard-template-plugin/utils/nodes.ts
  package.json
Labels: bug

#96 Fix insert-citation button not being enabled in correct context.
  addon/components/citation-plugin/citation-insert.ts
  addon/plugins/citation-plugin/index.ts
Labels: bug

#102 Fix: correcltly set the date type as xsd:date or xsd:dateTime based on the date content
  addon/components/rdfa-date-plugin/card.ts
  addon/plugins/rdfa-date-plugin/utils.ts
Labels: bug

#101 Add the __rdfaId when manually creating decisions titles, decision articles or citations
  addon/plugins/besluit-plugin/commands/insert-title.ts
  addon/plugins/citation-plugin/utils/cited-text.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#103 bump editor to v2.1.1
  package-lock.json
  package.json
Labels: internal

#104 fix citation highlights not triggering correctly in various situations
  addon/plugins/citation-plugin/index.ts
  addon/plugins/citation-plugin/utils/process-match.ts
Labels: bug

#106 Fix subsection 'move down' dutch translation
  CHANGELOG.md
  translations/nl-BE.yaml
Labels: bug

#109 Remove insert date and time as it's no longer needed
  addon/components/rdfa-date-plugin/insert.hbs
  addon/components/rdfa-date-plugin/insert.ts
Labels: bug

#110 Bugfix/fix translations warnings
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: internal

#107 Set selectable on false for structure-headers
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/structure-header.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: bug

#112 Added a new option to the structures to not support unwrap and made the article paragraphs the first structure to use this option
  addon/components/article-structure-plugin/structure-card.hbs
  addon/components/article-structure-plugin/structure-card.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Labels: enhancement

#113 Bump ember-power-select to 6.0.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: internal

#88 Update ember-source to 4.8.4
  .woodpecker/.release.yml
  .woodpecker/.test-scenarios.yml
  .woodpecker/.test.yml
  CHANGELOG.md
  README.md
  config/ember-try.js
  ember-cli-build.js
  package-lock.json
  package.json
  tests/dummy/config/ember-cli-update.json
Labels: internal

#114 Update editor to 3.2.0
  CHANGELOG.md
  addon/components/article-structure-plugin/article-structure-card.hbs
  addon/components/article-structure-plugin/article-structure-card.ts
  addon/components/article-structure-plugin/structure-card.ts
  addon/components/besluit-plugin/besluit-plugin-card.ts
  addon/components/besluit-type-plugin/toolbar-dropdown.hbs
  addon/components/besluit-type-plugin/toolbar-dropdown.ts
  addon/components/citation-plugin/citation-card.ts
  addon/components/citation-plugin/citation-insert.ts
  addon/components/import-snippet-plugin/card.ts
  addon/components/rdfa-date-plugin/card.ts
  addon/components/rdfa-date-plugin/insert.ts
  addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
  addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
  addon/components/roadsign-regulation-plugin/roadsigns-table.ts
  addon/components/standard-template-plugin/card.ts
  addon/components/standard-template-plugin/template-provider.ts
  addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.ts
  addon/components/table-of-contents-plugin/toolbar-button.ts
  addon/components/variable-plugin/insert-variable-card.ts
  addon/components/variable-plugin/template-variable-card.hbs
  addon/components/variable-plugin/template-variable-card.ts
  addon/components/variable-plugin/variable.hbs
  addon/components/variable-plugin/variable.ts
  addon/models/instruction.ts
  addon/models/measure.ts
  addon/models/sign.ts
  addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
  addon/plugins/article-structure-plugin/index.ts
  addon/plugins/article-structure-plugin/structures/article.ts
  addon/plugins/article-structure-plugin/structures/chapter.ts
  addon/plugins/article-structure-plugin/structures/section.ts
  addon/plugins/article-structure-plugin/structures/subsection.ts
  addon/plugins/article-structure-plugin/structures/title.ts
  addon/plugins/besluit-plugin/index.ts
  addon/plugins/besluit-plugin/utils/get-title-for-decision.ts
  addon/plugins/besluit-type-plugin/index.ts
  addon/plugins/citation-plugin/index.ts
  addon/plugins/import-snippet-plugin.ts
  addon/plugins/rdfa-date-plugin/index.ts
  addon/plugins/rdfa-date-plugin/nodes/date.ts
  addon/plugins/rdfa-date-plugin/nodes/index.ts
  addon/plugins/roadsign-regulation-plugin/index.ts
  addon/plugins/standard-template-plugin/index.ts
  addon/plugins/table-of-contents-plugin/index.ts
  addon/plugins/variable-plugin/index.ts
  addon/services/roadsign-registry.ts
  app/styles/besluit-plugin.scss
  package-lock.json
  package.json
  tests/dummy/app/components/dummy-container.hbs
  tests/dummy/app/components/rdfa-editor-with-debug.js
  tests/dummy/app/components/toolbar/history.hbs
  tests/dummy/app/components/toolbar/list.hbs
  tests/dummy/app/components/toolbar/styling.hbs
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/templates/besluit-sample.hbs
  tests/dummy/app/templates/regulatory-statement-sample.hbs
Labels: breaking

#115 Use AuModalContainer instead of #ember-appuniversum-wormhole element in dummy app
  CHANGELOG.md
  ember-cli-build.js
  tests/dummy/app/templates/application.hbs
Labels: internal

#116 Article paragraphs should not be numbered continuous
  CHANGELOG.md
  addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Labels: bug
