Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2024-11, with the labels that each got.

#494 GN-5153: only trigger event handlers of snippet actions once
  .changeset/fuzzy-pillows-relax.md
  addon/components/snippet-plugin/nodes/snippet.gts
Labels: bug

#500 Fix bug when setting 31/12/.. date
  .changeset/swift-fireants-dress.md
  addon/components/variable-plugin/date/date-time-picker.ts
Labels: bug

#499 Update `@lblod/ember-rdfa-editor` peerdependency requirement to 10.7.1
  .changeset/late-zoos-call.md
  .changeset/loud-moles-tease.md
  addon/components/mandatee-table-plugin/node.gts
  app/styles/mandatee-table-plugin.scss
  config/ember-try.js
  package.json
  pnpm-lock.yaml
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/controllers/snippet-edit-sample.ts
Labels: breaking

#501 Feat/add snippet list names to modal title
  .changeset/tough-pugs-shave.md
  addon/components/snippet-plugin/nodes/snippet.gts
  addon/components/snippet-plugin/search-modal.hbs
  addon/components/snippet-plugin/search-modal.ts
  addon/components/snippet-plugin/snippet-insert.gts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#504 GN-5217: person variable adjustments
  .changeset/metal-bags-pump.md
  .changeset/twelve-mugs-think.md
  .changeset/wild-walls-turn.md
  addon/components/lmb-plugin/insert.ts
  addon/components/lmb-plugin/list.hbs
  addon/components/lmb-plugin/search-modal.ts
  addon/components/variable-plugin/person/edit.ts
  addon/components/variable-plugin/person/nodeview.ts
  addon/models/electee.ts
  addon/models/mandatee.ts
  addon/plugins/lmb-plugin/index.ts
  addon/plugins/lmb-plugin/utils/fetchElectees.ts
  addon/plugins/lmb-plugin/utils/fetchMandatees.ts
  addon/plugins/variable-plugin/variables/person.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement, breaking

#505 Use the new template uris on variables
  .changeset/quiet-poems-float.md
  addon/components/lmb-plugin/insert.ts
  addon/components/location-plugin/insert.gts
  addon/components/variable-plugin/address/insert-variable.ts
  addon/components/variable-plugin/address/insert.ts
  addon/components/variable-plugin/address/utils.ts
  addon/components/variable-plugin/autofilled/insert.gts
  addon/components/variable-plugin/codelist/insert.ts
  addon/components/variable-plugin/date/insert-variable.ts
  addon/components/variable-plugin/date/insert.ts
  addon/components/variable-plugin/insert-variable-card.hbs
  addon/components/variable-plugin/location/insert.ts
  addon/components/variable-plugin/number/insert.ts
  addon/components/variable-plugin/person/insert.ts
  addon/components/variable-plugin/text/insert.ts
  addon/plugins/location-plugin/utils/node-utils.ts
  addon/plugins/variable-plugin/recreateUuidsOnPaste.ts
  tests/dummy/app/templates/regulatory-statement-sample.hbs
Labels: bug

#509 GN-5187: add clearer warning to mandatee table on losing changes
  .changeset/chilled-cooks-juggle.md
  addon/components/mandatee-table-plugin/node.gts
  app/styles/mandatee-table-plugin.scss
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#508 fix(decision-article): remove unnecessary css placeholder
  .changeset/smart-pigs-fly.md
  addon/components/structure-plugin/_private/structure.gts
  app/styles/structure-plugin.scss
Labels: bug

#507 update template-uuid-instantiator to 1.0.3
  .changeset/twenty-mugs-fail.md
  package.json
  pnpm-lock.yaml
Labels: internal
