Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2024-07, with the labels that each got.

#446 GN-4653: configurable, internationalized structure names
  .changeset/poor-cycles-approve.md
  addon/components/structure-plugin/_private/structure.gts
  addon/plugins/decision-plugin/utils/build-article-structure.ts
  addon/plugins/structure-plugin/node.ts
  addon/utils/translation.ts
  tests/dummy/app/controllers/besluit-sample.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#447 Ensure `zonality` is set up as optional when fetching traffic signs
  .changeset/few-dragons-kick.md
  addon/models/sign.ts
  addon/services/roadsign-registry.ts
Labels: bug

#444 GN-4897: ensure older decision articles can be correctly parsed into the new `structure` nodes
  .changeset/long-colts-knock.md
  .changeset/poor-cycles-approve.md
  addon/components/structure-plugin/_private/structure.gts
  addon/plugins/decision-plugin/utils/build-article-structure.ts
  addon/plugins/structure-plugin/node.ts
  addon/utils/translation.ts
  tests/dummy/app/controllers/besluit-sample.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#449 Drop obsolete decision nodes from standard-template plugin
  .changeset/ten-spiders-help.md
  addon/plugins/standard-template-plugin/index.ts
  addon/plugins/standard-template-plugin/utils/nodes.ts
Labels: breaking

#450 lmb-plugin: ensure independent mandatees (without a fraction) can be selected for insertion
  .changeset/fair-spoons-tell.md
  addon/components/lmb-plugin/search-modal.ts
  addon/models/mandatee.ts
Labels: bug

#451 Remove `node-type` based validation plugin
  .changeset/violet-plums-remain.md
  README.md
  addon/components/validation-plugin/validation-card.hbs
  addon/components/validation-plugin/validation-card.ts
  addon/components/validation-plugin/validation-item.hbs
  addon/components/validation-plugin/validation-item.ts
  addon/plugins/decision-plugin/utils/validation-rules.ts
  addon/plugins/validation/README.md
  addon/plugins/validation/index.ts
  addon/plugins/validation/utils/transaction-complies-with-shapes.ts
  app/components/validation-plugin/validation-card.js
  app/components/validation-plugin/validation-item.js
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: breaking

#457 Insert person was broken on the besluit sample page
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/templates/besluit-sample.hbs
Labels: bug

#459 Added body to templates
  .changeset/mean-donkeys-sip.md
  tests/dummy/app/controllers/besluit-sample.ts
Labels: bug
