Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2024-10, with the labels that each got.

#472 Gn 4901 autofill variable
  .changeset/mean-deers-call.md
  addon/components/variable-plugin/autofilled/edit.gts
  addon/components/variable-plugin/autofilled/insert.gts
  addon/components/variable-plugin/autofilled/nodeview.gts
  addon/components/variable-plugin/utils/label-input.gts
  addon/components/variable-plugin/utils/label-input.hbs
  addon/plugins/snippet-plugin/commands/insert-snippet.ts
  addon/plugins/variable-plugin/plugins/autofiller.ts
  addon/plugins/variable-plugin/variables/autofilled.ts
  addon/plugins/variable-plugin/variables/index.ts
  app/components/variable-plugin/autofilled/edit.js
  app/components/variable-plugin/autofilled/insert.js
  app/components/variable-plugin/autofilled/nodeview.js
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/templates/regulatory-statement-sample.hbs
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#484 GN-5004: add option to enable/disable multi-snippet insertion
  .changeset/olive-zebras-check.md
  addon/components/snippet-plugin/nodes/snippet.gts
  addon/components/snippet-plugin/snippet-insert-placeholder.gts
  addon/components/snippet-plugin/snippet-insert-rdfa.gts
  addon/components/snippet-plugin/snippet-insert.gts
  addon/components/snippet-plugin/snippet-list-select.gts
  addon/components/snippet-plugin/snippet-list/snippet-list-modal.hbs
  addon/components/snippet-plugin/snippet-list/snippet-list-modal.ts
  addon/plugins/snippet-plugin/commands/insert-snippet.ts
  addon/plugins/snippet-plugin/commands/update-snippet-placeholder.ts
  addon/plugins/snippet-plugin/nodes/snippet-placeholder.ts
  addon/plugins/snippet-plugin/nodes/snippet.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#482 GN-5005: adjust snippet queries to work with new snippet data-model
  .changeset/yellow-lamps-fly.md
  addon/plugins/citation-plugin/utils/public-decisions.ts
  addon/plugins/citation-plugin/utils/vlaamse-codex.ts
  addon/plugins/snippet-plugin/utils/fetch-data.ts
  addon/services/roadsign-registry.ts
Labels: enhancement, breaking

#486 Use a special name if you only have one article in the document
  .changeset/six-ants-appear.md
  addon/components/structure-plugin/_private/structure.gts
  addon/plugins/structure-plugin/node.ts
  addon/plugins/structure-plugin/recalculate-structure-numbers.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#490 Parse only article also from templates
  .changeset/mighty-mice-itch.md
  addon/plugins/structure-plugin/node.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: bug

#493 Redesign structure nodes v1
  .changeset/purple-bananas-beg.md
  app/styles/structure-plugin.scss
Labels: enhancement
