Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2025-04, with the labels that each got.

#557 Solved bug with powerselect dropdown not displaying in place
  .changeset/grumpy-clocks-jam.md
  addon/components/variable-plugin/location/edit.hbs
  app/styles/variable-plugin.scss
Labels: bug

#555 feat: add backward-compatible parserule to `roadsign_regulation` nodespec
  .changeset/rare-meals-jam.md
  addon/plugins/roadsign-regulation-plugin/nodes.ts
  package.json
  pnpm-lock.yaml
Labels: enhancement

#550 GN-5440: smart variables
  .changeset/brown-bats-watch-1.md
  .changeset/brown-bats-watch-2.md
  .changeset/brown-bats-watch-3.md
  .changeset/brown-bats-watch-4.md
  .changeset/brown-bats-watch-5.md
  .changeset/brown-bats-watch-6.md
  .changeset/brown-bats-watch-7.md
  .changeset/brown-bats-watch-8.md
  .changeset/plenty-spies-scream.md
  .changeset/stupid-eels-eat.md
  addon/components/lmb-plugin/insert.ts
  addon/components/location-plugin/insert.gts
  addon/components/variable-plugin/address/edit.ts
  addon/components/variable-plugin/address/insert.ts
  addon/components/variable-plugin/address/nodeview.ts
  addon/components/variable-plugin/address/utils.ts
  addon/components/variable-plugin/autofilled/edit.gts
  addon/components/variable-plugin/autofilled/insert.gts
  addon/components/variable-plugin/codelist/edit.ts
  addon/components/variable-plugin/codelist/insert.ts
  addon/components/variable-plugin/date/edit.ts
  addon/components/variable-plugin/date/insert-variable.ts
  addon/components/variable-plugin/date/insert.ts
  addon/components/variable-plugin/date/nodeview.ts
  addon/components/variable-plugin/location/edit.ts
  addon/components/variable-plugin/location/insert.ts
  addon/components/variable-plugin/number/insert.ts
  addon/components/variable-plugin/number/nodeview.ts
  addon/components/variable-plugin/person/edit.hbs
  addon/components/variable-plugin/person/edit.ts
  addon/components/variable-plugin/person/insert.ts
  addon/components/variable-plugin/person/nodeview.ts
  addon/components/variable-plugin/text/insert.ts
  addon/plugins/location-plugin/node.ts
  addon/plugins/snippet-plugin/nodes/snippet.ts
  addon/plugins/variable-plugin/actions/create-autofilled-variable.ts
  addon/plugins/variable-plugin/actions/create-classic-location-variable.ts
  addon/plugins/variable-plugin/actions/create-codelist-variable.ts
  addon/plugins/variable-plugin/actions/create-date-variable.ts
  addon/plugins/variable-plugin/actions/create-number-variable.ts
  addon/plugins/variable-plugin/actions/create-person-variable.ts
  addon/plugins/variable-plugin/actions/create-text-variable.ts
  addon/plugins/variable-plugin/utils/recreate-variable-uris.ts
  addon/plugins/variable-plugin/variables/autofilled.ts
  addon/plugins/variable-plugin/variables/codelist.ts
  addon/plugins/variable-plugin/variables/date.ts
  addon/plugins/variable-plugin/variables/location.ts
  addon/plugins/variable-plugin/variables/number.ts
  addon/plugins/variable-plugin/variables/person.ts
  addon/plugins/variable-plugin/variables/text.ts
  package.json
  pnpm-lock.yaml
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  tests/dummy/app/controllers/snippet-edit-sample.ts
Labels: enhancement

#562 fix(besluit-type-plugin): remove fetch-sparql-endpoint dep
  .changeset/lazy-spies-peel.md
  addon/models/electee.ts
  addon/plugins/besluit-type-plugin/utils/fetchBesluitTypes.ts
  package.json
  pnpm-lock.yaml
Labels: bug

#563 Improve title of structure card
  .changeset/friendly-suits-deliver.md
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#565 fix(citation-plugin): remove usage of unsupported `keyboardInstruction` argument
  .changeset/rotten-trainers-allow.md
  addon/components/citation-plugin/citations/search-modal.ts
Labels: bug

#564 Feat/make lpdc endpoint more configurable
  .changeset/gorgeous-rocks-cheer.md
  addon/plugins/lpdc-plugin/api.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: breaking
