Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2025-07, with the labels that each got.

#586 Category filter was not working on roadsign regulation plugin
  .changeset/early-jobs-joke.md
  addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
Labels: bug

#587 GN-5646: roadsign-regulation-plugin - fix variable signage feature
  .changeset/hip-steaks-dance.md
  addon/components/roadsign-regulation-plugin/expanded-measure.gts
  addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
Labels: bug

#584 location-plugin: add placeholder mode
  .changeset/serious-fishes-tell.md
  .eslintrc.js
  addon/components/location-plugin/insert-location-placeholder.gts
  addon/components/location-plugin/insert.gts
  addon/components/location-plugin/nodeview.gts
  addon/plugins/location-plugin/_private/node-contents/address.ts
  addon/plugins/location-plugin/_private/node-contents/area.ts
  addon/plugins/location-plugin/_private/node-contents/index.ts
  addon/plugins/location-plugin/_private/node-contents/place.ts
  addon/plugins/location-plugin/_private/node-contents/point.ts
  addon/plugins/location-plugin/_private/utils/address-helpers.ts
  addon/plugins/location-plugin/_private/utils/geo-helpers.ts
  addon/plugins/location-plugin/_private/utils/node-utils.ts
  addon/plugins/location-plugin/node-contents/address.ts
  addon/plugins/location-plugin/node-contents/area.ts
  addon/plugins/location-plugin/node-contents/index.ts
  addon/plugins/location-plugin/node-contents/place.ts
  addon/plugins/location-plugin/node-contents/point.ts
  addon/plugins/location-plugin/node.ts
  addon/plugins/location-plugin/utils/address-helpers.ts
  addon/plugins/location-plugin/utils/geo-helpers.ts
  addon/plugins/location-plugin/utils/node-utils.ts
  app/components/location-plugin/insert-location-placeholder.js
  tests/dummy/app/templates/besluit-sample.hbs
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#590 rename traffic-sign to traffic-signal
  .changeset/breezy-humans-design.md
  addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
  addon/components/roadsign-regulation-plugin/roadsigns-table.gts
  addon/plugins/roadsign-regulation-plugin/actions/insert-measure.ts
  addon/plugins/roadsign-regulation-plugin/constants.ts
  addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
  addon/plugins/roadsign-regulation-plugin/queries/traffic-signal-codes.ts
  addon/plugins/roadsign-regulation-plugin/queries/traffic-signal-concept.ts
  addon/plugins/roadsign-regulation-plugin/schemas/mobility-measure-concept.ts
  addon/plugins/roadsign-regulation-plugin/schemas/sign-code.ts
  addon/plugins/roadsign-regulation-plugin/schemas/traffic-signal-code.ts
  addon/plugins/roadsign-regulation-plugin/schemas/traffic-signal-concept.ts
  tests/dummy/app/controllers/besluit-sample.ts
Labels: internal

#591 Fix traffic measure type filter
  .changeset/fast-ladybugs-admire.md
  .changeset/late-radios-joke.md
  addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
  addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
Labels: bug
