Repository lblod/ember-rdfa-editor-lblod-plugins, pull requests merged in 2025-01, with the labels that each got.

#523 Redesign of fragment nodes
  .changeset/fluffy-carrots-drum.md
  addon/components/snippet-plugin/nodes/snippet.gts
  app/styles/snippet-plugin.scss
Labels: enhancement

#525 Feat/convert snippet plugin to uris
  .changeset/cold-tomatoes-enjoy.md
  addon/components/snippet-plugin/nodes/snippet.gts
  addon/components/snippet-plugin/search-modal.ts
  addon/components/snippet-plugin/snippet-insert-placeholder.gts
  addon/components/snippet-plugin/snippet-insert-rdfa.gts
  addon/components/snippet-plugin/snippet-insert.gts
  addon/components/snippet-plugin/snippet-list-select.gts
  addon/components/snippet-plugin/snippet-list/snippet-list-modal.hbs
  addon/components/snippet-plugin/snippet-list/snippet-list-modal.ts
  addon/components/snippet-plugin/snippet-list/snippet-list-view.hbs
  addon/components/snippet-plugin/snippet-list/snippet-list-view.ts
  addon/plugins/snippet-plugin/commands/update-snippet-placeholder.ts
  addon/plugins/snippet-plugin/index.ts
  addon/plugins/snippet-plugin/nodes/snippet-placeholder.ts
  addon/plugins/snippet-plugin/nodes/snippet.ts
  addon/plugins/snippet-plugin/utils/fetch-data.ts
  addon/plugins/snippet-plugin/utils/rdfa-predicate.ts
  addon/utils/sparql-helpers.ts
Labels: internal

#530 Move to builtin ember types
  .changeset/violet-mangos-deliver.md
  addon/components/location-plugin/edit.gts
  addon/utils/translation.ts
  package.json
  pnpm-lock.yaml
  tests/dummy/app/controllers/besluit-sample.ts
  tests/dummy/app/controllers/regulatory-statement-sample.ts
  types/dummy/index.d.ts
Labels: internal

#531 bugfix: cleanup incorrect attribute serializations
  .changeset/hot-mugs-decide.md
  addon/plugins/snippet-plugin/nodes/snippet.ts
  addon/plugins/variable-plugin/variables/autofilled.ts
  addon/plugins/variable-plugin/variables/text.ts
Labels: bug

#521 GN-4881: support for truncated addresses
  .changeset/hot-comics-act.md
  addon/components/location-plugin/edit.gts
  addon/plugins/location-plugin/node-contents/address.ts
  addon/plugins/location-plugin/utils/address-helpers.ts
  addon/utils/namespace.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: enhancement

#532 fix: prevent `write-after-read` error in codelist and location edit components
  .changeset/thin-pandas-provide.md
  addon/components/variable-plugin/codelist/edit.ts
  addon/components/variable-plugin/location/edit.ts
  translations/en-US.yaml
  translations/nl-BE.yaml
Labels: bug
